package exception

import "errors"

var AlreadyHookExistsError = errors.New("Hook is already exists ")
